apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akkar
spec:
  destination:
    name: ''
    namespace: akkar
    server: 'https://kubernetes.default.svc'
  source:
    path: app
    repoURL: 'https://github.com/stianfro/argo-lab.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true