apiVersion: apps/v1
kind: Deployment
metadata:
  name: akkar
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80