apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: akkar-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: akkar.froystein.xyz
    http:
      paths:
      - backend:
          serviceName: akkar-service
          servicePort: 80
        path: /